// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ryJvFOJy3jo6Fn8Y4iPoQTNzdwKHifk',
    appId: '1:277705410335:web:6661796f592a9d6c0c122a',
    messagingSenderId: '277705410335',
    projectId: 'ecommerce-app-460ef',
    authDomain: 'ecommerce-app-460ef.firebaseapp.com',
    storageBucket: 'ecommerce-app-460ef.firebasestorage.app',
    measurementId: 'G-H2HS9XS570',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk23sbDh9hGZfUXvjPMrE8gpCs7Ptezv4',
    appId: '1:277705410335:android:8fe65ae0eb346e1b0c122a',
    messagingSenderId: '277705410335',
    projectId: 'ecommerce-app-460ef',
    storageBucket: 'ecommerce-app-460ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoq_yLWArqUKJCgcdX1srMlMnuJK3TE1U',
    appId: '1:277705410335:ios:0db59b62853a91520c122a',
    messagingSenderId: '277705410335',
    projectId: 'ecommerce-app-460ef',
    storageBucket: 'ecommerce-app-460ef.firebasestorage.app',
    iosClientId: '277705410335-i2sk161rm9gf9f9snvmr2n9k750mbcmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoq_yLWArqUKJCgcdX1srMlMnuJK3TE1U',
    appId: '1:277705410335:ios:0db59b62853a91520c122a',
    messagingSenderId: '277705410335',
    projectId: 'ecommerce-app-460ef',
    storageBucket: 'ecommerce-app-460ef.firebasestorage.app',
    iosClientId: '277705410335-i2sk161rm9gf9f9snvmr2n9k750mbcmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ryJvFOJy3jo6Fn8Y4iPoQTNzdwKHifk',
    appId: '1:277705410335:web:19b08bc3554b701f0c122a',
    messagingSenderId: '277705410335',
    projectId: 'ecommerce-app-460ef',
    authDomain: 'ecommerce-app-460ef.firebaseapp.com',
    storageBucket: 'ecommerce-app-460ef.firebasestorage.app',
    measurementId: 'G-6B9FMDEJK5',
  );
}
